current_data = ""

dataset_paths = {
	'celeba_train': '',
	'celeba_test': '',
	'celeba_train_sketch': '',
	'celeba_test_sketch': './path/to/last_project/test',
	'celeba_train_segmentation': '',
	'celeba_test_segmentation': '',
	'ffhq': '',
	'texture_train_source': 'path/to/ori/B/val',
	'texture_train_target': 'path/to/ori/A/val',
	'texture_test_source': 'path/to/ori/B/test',
	'texture_test_target': 'path/to/ori/A/test',
	'ffhq_source': '/home/jinguodong/data/final_data/ori/train',
	'ffhq_target': '/home/jinguodong/data/final_data/uv/train',
	'ffhq_test_source': '/home/jinguodong/data/final_data/ori/test',
	'ffhq_test_target': '/home/jinguodong/data/final_data/uv/test',
	'render_train_source': '/home/jinguodong/data/final_data/render/train',
	'render_test_source': '/home/jinguodong/data/final_data/render/test',
	'render_train_target': '/home/jinguodong/data/final_data/uv12/train',
	'render_test_target': '/home/jinguodong/data/final_data/uv12/test',
	'render_train_source_5k': '/home/jinguodong/data/aug/render/train',
	'render_test_source_5k': '/home/jinguodong/data/aug/render/test',
	'render_train_target_5k': '/home/jinguodong/data/aug/uv/train',
	'render_test_target_5k': '/home/jinguodong/data/aug/uv/test',
	'render_train_source_5k_8d': '/home/jinguodong/data/aug/render_8d/train',
	'render_test_source_5k_8d': '/home/jinguodong/data/aug/render_8d/test',
	'render_train_target_5k_8d': '/home/jinguodong/data/aug/uv_8d/train',
	'render_test_target_5k_8d': '/home/jinguodong/data/aug/uv_8d/test',
	'wild_1650_train_source': '/home/jinguodong/data/seg/seg_1650/train',
	'wild_1650_test_source': '/home/jinguodong/data/seg/seg_1650/test',
	'wild_1650_train_target': '/home/jinguodong/data/seg/uv_1650/train',
	'wild_1650_test_target': '/home/jinguodong/data/seg/uv_1650/test',
	'eye_1386_train_source': '/home/jinguodong/data/seg/seg_1261/train',
	'eye_1386_test_source': '/home/jinguodong/data/seg/seg_1261/test',
	'eye_1386_train_target': '/home/jinguodong/data/eyes/eye_512_1386/train',
	'eye_1386_test_target': '/home/jinguodong/data/eyes/eye_512_1386/test',
	'back_1386_train_source': '/home/jinguodong/data/final_data/render/train',
	'back_1386_test_source': '/home/jinguodong/data/final_data/render/test',
	'back_1386_train_target': '/home/jinguodong/data/back_uv/uv_1650/train',
	'back_1386_test_target': '/home/jinguodong/data/back_uv/uv_1650/test',
	'back_4592_train_source': '/home/jinguodong/data/back_uv/aug/render_4592/train',
	'back_4592_test_source': '/home/jinguodong/data/back_uv/aug/render_4592/test',
	'back_4592_train_target': '/home/jinguodong/data/back_uv/aug/uv_4592/train',
	'back_4592_test_target': '/home/jinguodong/data/back_uv/aug/uv_4592/test',
	# head_global_4592
	'head_4592_train_target': '/home/jinguodong/data/merge/head/uv_4592/train',
	'head_4592_test_target': '/home/jinguodong/data/merge/head/uv_4592/test',
	'head_4592_train_source': '/home/jinguodong/data/merge/head/render_4592/train',
	'head_4592_test_source': '/home/jinguodong/data/merge/head/render_4592/test',
	# nose_single_4592
	'nose_4592_train_source': '/home/jinguodong/data/merge/nose/render_4592/train',
	'nose_4592_test_source': '/home/jinguodong/data/merge/nose/render_4592/test',
	'nose_4592_train_target': '/home/jinguodong/data/merge/nose/uv_4592/train',
	'nose_4592_test_target': '/home/jinguodong/data/merge/nose/uv_4592/test',
	# mouth_single_4592
	'mouth_4592_train_source': '/home/jinguodong/data/merge/mouth/render_4592/train',
	'mouth_4592_test_source': '/home/jinguodong/data/merge/mouth/render_4592/test',
	'mouth_4592_train_target': '/home/jinguodong/data/merge/mouth/uv_4592/train',
	'mouth_4592_test_target': '/home/jinguodong/data/merge/mouth/uv_4592/test',
	# body_single_4592
	'body_4592_train_source': '/program/huawei/something/datasets/render_masked',
	'body_4592_test_source': '/program/huawei/something/datasets/render_masked_test',
	'body_4592_train_target': '/program/huawei/something/datasets/uv_render',
	'body_4592_test_target': '/program/huawei/something/datasets/uv_render_test',
}

model_paths = {
	'stylegan_ffhq': 'pretrained_models/stylegan2-ffhq-config-f.pt',
	'ir_se50': '/home/jinguodong/data/models/p2style2p/pretrained_models/model_ir_se50.pth',
	'circular_face': 'pretrained_models/CurricularFace_Backbone.pth',
	'mtcnn_pnet': 'pretrained_models/mtcnn/pnet.npy',
	'mtcnn_rnet': 'pretrained_models/mtcnn/rnet.npy',
	'mtcnn_onet': 'pretrained_models/mtcnn/onet.npy',
	'shape_predictor': 'shape_predictor_68_face_landmarks.dat',
	'moco': 'pretrained_models/moco_v2_800ep_pretrain.pt'
}
